config/routes.rb
Rails.application.routes.draw do

  # get "log_in", to: "users#login"
  root "main#index"
  
  get "userupdate", to: "userupdates#edit", as: :edit_userupdate
  post "userupdate", to: "userupdates#edit"
  patch "userupdate", to: "userupdates#update"
  
  get "about", to: "main#index"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :users
  # resources :sessions
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
 attribute :user
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    enum :user_type,    {developer: 0, manager: 1, qa: 2 }
    validates :name, presence: true
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: true
    validates :password, presence: true
    validates :user_type, presence: true

    has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user 

    def set_current_user
        if session[:user_id]
            Current.user=User.find_by(id: session[:user_id])
        end
    end

    def require_user_logged_in!
        redirect_to login_path, alert: "You must login to do that" if Current.user.nil?
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
   
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user=User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password]) 
      session[:user_id]=user.id
      redirect_to root_path
    else
      render :new, notice: "Invalid credentials"
    end
  end

  def destroy
    session[:user_id]=nil
    redirect_to root_path
  end



  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :user_type)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end
    def show
        Current.user=User.find_by(id: session[:user_id])
    end
    def new
        @user = User.new
    end
    def create
        @user=User.new(user_params)

        if @user.save
            session[:user_id]=@user.id
            redirect_to root_path
        else
            render :new, status: :unprocessable_entity
        end 
    end
    
    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to root_path, status: :see_other
    end




    private
    def user_params
        params.require(:user).permit(:name, :email, :password, :user_type)
    end
end

app/controllers/userupdates_controller.rb
class UserupdatesController < ApplicationController
    before_action :require_user_logged_in!

    def edit
    end
    def update
        if Current.user.update(user_params)
            redirect_to root_path, notice: "Profile updated successfully!!!"
        else
            render :edit, status: :unprocessable_entity
        end 
    end
end

private
def user_params
    params.require(:user).permit(:name, :email, :password, :user_type)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BugsTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render partial: "shared/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<p id="notice"><%= notice %></p>
<div class="d-flex align-items-center justify-content-center">
  <% if Current.user %>
    <% if Current.user.user_type=="manager"%>
        <h1>You are <%= Current.user.user_type%></h1>
    <% elsif Current.user.user_type="qa" %>
        <h1>You are <%= Current.user.user_type%></h1>
    <%else%>
        <h1>You are <%= Current.user.user_type%></h1>
    <% end %>
 <%end%>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
       <%= link_to "Navbar", root_path, class: "nav-link"%>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <%= link_to "Home", root_path, class: "nav-link"%>
          <%= link_to "About", about_path, class: "nav-link"%>
        </div>

        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <% if Current.user %>
            <li class="nav-item">
             <span class="navbar-text"> <%= Current.user.email %></span>
            </li>
            <li class="nav-item">
              <%= button_to "Logout", logout_path, method: :delete, class: "nav-link" %>
            </li>
             <li class="nav-item">
              <%= link_to "Edit", edit_userupdate_path, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Sign Up", new_user_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign In", login_path, class: "nav-link" %>
            </li>
           <% end %>
        </ul>

      </div>
    </div>
  </nav>

app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
    <div>
      <%= form.label :name %><br>
      <%= form.text_field :name, placeholder: "Mike" %>
       <% user.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
    </div>
    <div>
      <%= form.label :email %><br>
      <%= form.email_field :email, placeholder: "email@email.com" %>
       <% user.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
    </div>
    <div>
      <%= form.label :password %><br>
      <%= form.password_field :password, placeholder: "password" %>
       <% user.errors.full_messages_for(:password).each do |message| %>
      <div><%= message %></div>
    <% end %>
    </div>
    <div>
      <%= form.label :user_type %><br>
      <%= form.select :user_type, options_for_select(User.user_types.map {|key, value| [key.titleize, User.user_types.key(value)]}, user.user_type) %>
       <% user.errors.full_messages_for(:user_type).each do |message| %>
      <div><%= message %></div>
    <% end %>
    </div>
    <div>
    <%= form.submit%>
    </div>
<%end%>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= render "form", user: @user%>

app/views/users/new.html.erb
<h1>Registeration Form</h1>
<%= render "form", user: @user %>  

app/views/users/show.html.erb
<h1><%= @user.name%></h1>
<p><%= @user.user_type%>
<%= button_to "Logout", logout_path, method: :delete %>
<ul>
    <li> <%= link_to "Edit", edit_user_path(@user) %> </li>
    <li><%= link_to "Destory", user_path(@user), data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
    } %> </li>
</ul>

app/views/userupdates/edit.html.erb
<h1>Edit User</h1>
<%= form_with model: Current.user, url: edit_userupdate_path do |form| %>
    <div>
      <%= form.label :name %><br>
      <%= form.text_field :name, placeholder: "enter a name" %>
       
    </div>
    <div>
      <%= form.label :email %><br>
      <%= form.email_field :email, placeholder: "email@email.com" %>
       
    </div>
    <div>
      <%= form.label :password %><br>
      <%= form.password_field :password, placeholder: "password" %>
      
    </div>
    <div>
      <%= form.label :user_type %><br>
      <%= form.select :user_type, options_for_select(User.user_types.map {|key, value| [key.titleize, User.user_types.key(value)]}, Current.user.user_type) %>
       
    </div>
    <div>
    <%= form.submit "Update", class: "btn btn-primary" %>
    </div>
<%end%>